name: Oocana mount Image
# Builds Oocana container image with oocana CLI and ovmlayer.
# Does NOT include executor layers and ovmlayer's rootfs those are separate tar artifacts.
# this image need mount rootfs so that ovmlayer can work properly.

on:
  pull_request:
    paths:
      - "dockerfiles/oocana-mount.dockerfile"
      - "package.json"
      - "package-lock.json"
      - "scripts/entrypoint.sh"
      - ".github/workflows/image-oocana.yml"
  push:
    tags:
      - 'oocana-mount**'
    branches:
      - main
    paths:
      - "dockerfiles/oocana-mount.dockerfile"
      - "package.json"
      - "package-lock.json"
      - "scripts/entrypoint.sh"
      - ".github/workflows/image-oocana.yml"
  workflow_dispatch:

env:
  IMAGE_NAME: oocana-mount

jobs:
  build-oocana-mount:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/oomol/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}},match=${{ env.IMAGE_NAME }}@(\d+\.\d+\.\d+)
          flavor: |
            latest=auto
          labels: |
            org.opencontainers.image.description=A container for running Oocana directly in command line.
      - name: Prepare build context (arm64)
        uses: ./.github/actions/build-context
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          architecture: arm64
          ovmlayer_app_id: ${{ vars.OOMOL_DOWNLOADER_APP_ID }}
          ovmlayer_app_private_key: ${{ secrets.OOMOL_DOWNLOADER_APP_PRIVATE_KEY }}
      - name: Prepare build context (amd64)
        uses: ./.github/actions/build-context
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          architecture: amd64
          ovmlayer_app_id: ${{ vars.OOMOL_DOWNLOADER_APP_ID }}
          ovmlayer_app_private_key: ${{ secrets.OOMOL_DOWNLOADER_APP_PRIVATE_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || startsWith(github.ref, 'refs/tags/oocana-mount') }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: dockerfiles/oocana-mount.dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max